/**
 * Supported categories for POV scenes.
 * Used for filtering and prompting the AI.
 */
export enum Category {
  Action = 'Action',
  Adventure = 'Adventure',
  SciFi = 'Sci-Fi',
  Fantasy = 'Fantasy',
  Cyberpunk = 'Cyberpunk',
  Neon = 'Neon',
  Military = 'Military',
  Supernatural = 'Supernatural',
  Horror = 'Horror',
  Nature = 'Nature',
  Underwater = 'Underwater',
  UrbanLife = 'Urban Life',
  Space = 'Space',
  Sports = 'Sports',
  Historical = 'Historical',
  Mythological = 'Mythological',
  Surreal = 'Surreal',
  Dreamlike = 'Dreamlike',
  Architectural = 'Architectural',
  EverydayLife = 'Everyday Life'
}

/**
 * Represents a single generated scene concept.
 * Contains both text data and UI state for image generation.
 */
export interface SceneConcept {
  /** Unique identifier for the scene (1-1000) */
  id: number;
  /** The cinematic description generated by the AI */
  description: string;
  /** The genre/category of the scene */
  category: string;
  /** Description of the lighting conditions */
  lighting: string;
  /** Description of the camera angle/movement */
  camera: string;
  /** Data URL or remote URL for the thumbnail image */
  thumbnailUrl?: string;
  /** UI state: is the thumbnail currently generating? */
  isGeneratingThumbnail?: boolean;
  /** Data URL for the high-resolution image (Pro model) */
  highResUrl?: string;
  /** UI state: is the high-res image currently generating? */
  isGeneratingHighRes?: boolean;
  /** User preference: is this scene favorited? */
  isFavorite?: boolean;
}

/**
 * Global statistics for the current generation session.
 */
export interface GenerationStats {
  /** Total number of text scenes generated so far */
  totalGenerated: number;
  /** Number of API batches completed */
  batchesCompleted: number;
  /** Global state: is the text generation loop active? */
  isGenerating: boolean;
  /** Timestamp when generation started */
  startTime: number | null;
  /** Seconds elapsed since generation started */
  elapsedTime: number;
}

/**
 * UI Theme preference options.
 */
export type ThemeMode = 'default' | 'high-contrast';

/**
 * Structure for toast notifications.
 */
export interface ToastMessage {
  id: number;
  message: string;
  type: 'success' | 'error' | 'info';
}